name: flutterph
description: The official website of Flutter Philippines

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.3.2+2
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^1.1.0+2

flutter:
  uses-material-design: true
